mitm:
  enabled: true
  ca_p12: egern.p12
  ca_passphrase: egern
  hostnames:
  - mobile-api.adguard.org
  - %APPEND% api.revenuecat.com
  - premium*.truecaller.com
  - api.picsart.com
  - buy.itunes.apple.com

header_rewrites:
- delete:
    match: ^https?://api.revenuecat.com/.+/(receipts$|subscribers/?(.*?)*$)
    name: X-RevenueCat-ETag
    type: request
- delete:
    match: ^https?://api.revenuecat.com/.+/(receipts$|subscribers/?(.*?)*$)
    name: x-revenuecat-etag
    type: request

- http_response:
    name: TrueCaller
    match: ^https://premium-(.+)\.truecaller\.com/v\d/(subscriptions|products\/apple)?
    script_url: https://raw.githubusercontent.com/tori2105/iOS-App-Scripts/main/js/TrueCaller.js
    body_required: true
- http_response:
    name: LocketRes
    match: ^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$)
    script_url: https://raw.githubusercontent.com/tori2105/iOS-App-Scripts/main/js/LocketRes.js
    body_required: true
    update_interval: 5
- http_request:
    name: LocketReq
    match: ^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers)
    script_url: https://raw.githubusercontent.com/tori2105/iOS-App-Scripts/main/js/LocketReq.js
    body_required: true
    update_interval: 5
- http_request:
    name: PicsArt
    match: https://api.picsart.com/gw-v2/shop/subscription/apple/purchases
    script_url: https://raw.githubusercontent.com/tori2105/iOS-App-Scripts/main/js/PicsArt.js
    body_required: true
    update_interval: 5
- http_response:
    name: AdGuard
    match: ^https:\/\/mobile-api\.adguard\.org\/api\/.+\/ios_validate_receipt\/(.*?)
    script_url: https://raw.githubusercontent.com/tori2105/iOS-App-Scripts/main/js/AdGuard.js
    body_required: true
    update_interval: 5
- http_response:
    name: iTunes
    match: ^https:\/\/buy\.itunes\.apple\.com\/verifyReceipt
    script_url: https://raw.githubusercontent.com/tori2105/iOS-App-Scripts/main/js/iTunes.js
    body_required: true
    update_interval: 5
